/opt/conda/envs/py_3.10/bin/cmake \
  -S /test_ck_yanxishi/flash_ck \
  -B /test_ck_yanxishi/flash_ck/build/cmake \
  -DPython_EXECUTABLE=/opt/conda/envs/py_3.10/bin/python3.10 \
  -DPython_INCLUDE_DIR=/opt/conda/envs/py_3.10/include/python3.10 \
  -DCMAKE_BUILD_TYPE=Release \
  -DCMAKE_INSTALL_PREFIX=/test_ck_yanxishi/flash_ck \
  -DCMAKE_PREFIX_PATH=/opt/rocm \
  -DROCM_PATH=/opt/rocm \
  -DHIP_PATH=/opt/rocm \
  -DCMAKE_CXX_COMPILER=/opt/rocm/bin/hipcc \
  -DGPU_TARGETS=gfx90a \
  -Dpybind11_DIR=/opt/conda/envs/py_3.10/lib/python3.10/site-packages/pybind11/share/cmake/pybind11 \
  -GNinja \
  -D CMAKE_PREFIX_PATH=`python3 -c 'import torch;print(torch.utils.cmake_prefix_path)'`
