[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "torch>=2.1",
    "cmake>=3.21",
    "ninja",
    "pip",
    "pybind11[global]>=2.12"
]

# Use legacy backend to import local packages in setup.py
build-backend = "setuptools.build_meta:__legacy__"



